### ISSUE TITLE
go vet fail with dependent library

### ISSUE THREAD

**Issue by MaitreDede** [testcontainers/testcontainers-go#127]
**Describe the bug**
`go vet ./...`
```
        github.com/testcontainers/testcontainers-go imports
        github.com/docker/docker/pkg/archive imports
        github.com/Sirupsen/logrus: github.com/Sirupsen/logrus@v1.4.2: parsing go.mod:
        module declares its path as: github.com/sirupsen/logrus
                but was required as: github.com/Sirupsen/logrus
```
https://github.com/sirupsen/logrus/issues/1041

**To Reproduce**
Referencing `github.com/testcontainers/testcontainers-go v0.0.10`

**Expected behavior**
The error should not appear.

**Additional context**
It seams that the `https://github.com/docker/docker` repo redirects to `https://github.com/moby/moby`. Maybe upgrade the docker lib dependency ?

**Comment by MaitreDede** [comment]
A possible workaround :

Add [https://github.com/testcontainers/testcontainers-go/blob/master/go.mod#L3](this line) to my project `go.mod`:

```
replace github.com/docker/docker => github.com/docker/engine v0.0.0-20190717161051-705d9623b7c1
```

**Comment by thaJeztah** [comment]
Adding a `replace` works if you want to use a version that matches a tagged release of docker (for which tags can be found in the `docker/engine` repository), but if that's the reason, it's probably most most logical to pick a tag (but pin by commit, because Go doesn't accept the YY.MM tags)

Unfortunately, the `replace` won't help for consumers of this project though (only for the project itself); the `replace` is not inherited by those projects, so everyone using this package would need to add the same replace rule to their `go.mod`.

The additional problem is that Go 1.13 also changed some things in how it interprets the "fake" versions, which may be the culprit here.

A similar discussion can be found here as well; https://github.com/moby/buildkit/pull/1297

**Comment by fbiville** [comment]
I'm currently trying to add testcontainers to https://github.com/markfisher/rokn/, i.e. `go get github.com/testcontainers/testcontainers-go` and get the exact same error as in the initial description.

**Comment by thaJeztah** [comment]
Yes, you'll have to manually specify the correct version some more details in https://github.com/moby/moby/issues/39302#issuecomment-635253855

**Comment by thaJeztah** [comment]
FWIW, all tags from the docker/engine repository have been added to the upstream docker/docker (moby/moby) repository, so it should no longer be needed to use the docker/engine repository

**Comment by gianarb** [comment]
Thanks @thaJeztah ! @fbiville it is not something we can fix in testcontainers. You have to replace `docker/docker` in your go mod with a specific tag.
https://github.com/golang/go/wiki/Modules#when-should-i-use-the-replace-directive

**Comment by gianarb** [comment]
Go vet is now working and it is part of CI.
Thanks!
