### ISSUE TITLE
Non-existent container image put test into an infinite loop

### ISSUE THREAD

**Issue by nikolayk812** [testcontainers/testcontainers-go#153]
**Describe the bug**
Test does not fail but stuck in an infinite loop in case of starting a non-existent container

**To Reproduce**
Try to start a test with Postgres version 10.12-alpine started by TC lib. The test never fails but stuck.

**Expected behavior**
The test should wait after a specific timeout

**Comment by nikolayk812** [comment]
How to reproduce: use non-existing image version, put breakpoint to github.com/cenkalti/backoff/retry.go L37 and another one to github.com/testcontainers/testcontainers-go/docker.go L407. It looks like the for-loop never return and it just keeps trying over and over again.

**Comment by ClaytonNorthey92** [comment]
hey @nikolayk812 could you put your test code here? I specifically would like to see the values in `ContainerRequest`

**Comment by gianarb** [comment]
@ClaytonNorthey92 @nikolayk812 
This may be related https://github.com/testcontainers/testcontainers-go/pull/155#pullrequestreview-359577805

**Comment by erdemtoraman** [comment]
The issue was that the retry logic for pulling the image didn't take the context cancellation into account as it didn't use the backoff with context and the backoff's max waiting duration defaults to 15 minutes which gave an impression of getting stuck forever. Additionally there is a way to terminate the retry mechanism by wrapping the error as permanent which should be done if the server return 404 for the requested image
