### ISSUE TITLE
[Enhancement]: Add amazon/dynamodb-local module

### ISSUE THREAD

**Issue by fpozzobon** [testcontainers/testcontainers-go#1620]
### Proposal

It is possible to use [localstack](https://github.com/testcontainers/testcontainers-go/tree/main/modules/localstack) module to run dynamodb but it is quite generic and difficult to implement for dynamodb.

Adding module for dynamodb using [amazon/dynamodb-local](https://hub.docker.com/r/amazon/dynamodb-local) image instead would make it easier to run dynamodb using testcontainers. 

It could also implement a method to get custom resolver and/or aws configuration and/or dynamo client connected to this database.

Example of interface:
```
dynamoContainer, err := dynamodb.RunContainer(ctx,
		testcontainers.WithImage("amazon/dynamodb-local:latest")
       )
	if err != nil {
		panic(err)
	}

	// Clean up the container
	defer func() {
		if err := dynamoContainer.Terminate(ctx); err != nil {
			panic(err)
		}
	}()
	// }

	state, err := dynamoContainer.State(ctx)
	if err != nil {
		panic(err)
	}
```

**Comment by mdelapenya** [comment]
Hey @fpozzobon thanks for opening this module request. I know that the localstack module already uses dynamodb-local under the hood, so I'm not totally sure about this request. Embedding the dynamo client into the module is a thing we try to avoid as much as possible, as we want our modules to be as much agnostic as possible to let users consume in their preferred way (e.g. HTTP calls, client calls). We do usually add examples on how to consume them, that's why many times we add the Go client for a given technology, but it's used only in the tests, not in the module itself.

So I'd initially reject this feature request for those reasons.

On the other hand, I'll be more than happy if you just implement it on your way, host it in a repo, and make it public through our modules catalog: https://github.com/testcontainers/community-module-registry/. Wdyt?

**Comment by fpozzobon** [comment]
@mdelapenya thanks for your recommendation, makes sense, I created a "blue print" example [here](https://github.com/fpozzobon/testcontainers-ddb-example-go/tree/main) it seems straight forward enough without need of module indeed.
