### ISSUE TITLE
[Bug]: Disabling AutoRemove is not working

### ISSUE THREAD

**Issue by fkorotkov** [testcontainers/testcontainers-go#1792]
### Testcontainers version

0.25.0

### Using the latest Testcontainers version?

Yes

### Host OS

macOS

### Host arch

ARM

### Go version

1.21

### Docker version

```shell
Client:
 Cloud integration: v1.0.35+desktop.5
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:28:49 2023
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.24.2 (124339)
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:31:36 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Docker info

```shell
Client:
 Version:    24.0.6
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.2-desktop.5
    Path:     /Users/fedor/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.22.0-desktop.2
    Path:     /Users/fedor/.docker/cli-plugins/docker-compose
  dev: Docker Dev Environments (Docker Inc.)
    Version:  v0.1.0
    Path:     /Users/fedor/.docker/cli-plugins/docker-dev
  extension: Manages Docker extensions (Docker Inc.)
    Version:  v0.2.20
    Path:     /Users/fedor/.docker/cli-plugins/docker-extension
  init: Creates Docker-related starter files for your project (Docker Inc.)
    Version:  v0.1.0-beta.8
    Path:     /Users/fedor/.docker/cli-plugins/docker-init
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc.)
    Version:  0.6.0
    Path:     /Users/fedor/.docker/cli-plugins/docker-sbom
  scan: Docker Scan (Docker Inc.)
    Version:  v0.26.0
    Path:     /Users/fedor/.docker/cli-plugins/docker-scan
  scout: Docker Scout (Docker Inc.)
    Version:  v1.0.7
    Path:     /Users/fedor/.docker/cli-plugins/docker-scout

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 2
 Server Version: 24.0.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8165feabfdfe38c65b599c4993d227328c231fca
 runc version: v1.1.8-0-g82f18fe
 init version: de40ad0
 Security Options:
  seccomp
   Profile: unconfined
  cgroupns
 Kernel Version: 6.4.16-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 10
 Total Memory: 7.667GiB
 Name: docker-desktop
 ID: a8fee3a0-9dfd-40d2-b2b5-20024cebd70e
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5555
  127.0.0.0/8
 Live Restore Enabled: false
```

### What happened?

I'm trying to use Testcontainers for a "dev" mode of an application. In a "dev" mode I'd love to have a locally running MongoDB. The logic I want to reproduce is the following: 

- before starting the app will check if there is a container named `mongodb-dev` exists
  -  if `mongodb-dev` is already running then do nothing
  - if `mongodb-dev` is not running than start it
  - if `mongodb-dev` doesn't exist then create it

I immediately though of using Testcontainers since we use them in tests. And it seems setting `Reuse` option to `true` and `AutoRemove` option to `false` should achieve my requirements. But with the code snippet below I experience that the `mongodb-dev` is removed after the program exits.

So it seems `AutoRemove` option is not respected in this scenario.

```go
package main

import (
	"context"
	"github.com/docker/docker/api/types/container"
	"github.com/testcontainers/testcontainers-go"
	"github.com/testcontainers/testcontainers-go/modules/mongodb"
	"time"
)

func main() {
	containerTemplate := testcontainers.GenericContainerRequest{
		ContainerRequest: testcontainers.ContainerRequest{
			Name: "mongodb-dev",
			HostConfigModifier: func(config *container.HostConfig) {
				config.AutoRemove = false
			},
		},
		Reuse: true,
	}
	mongodbContainer, err := mongodb.RunContainer(context.Background(), testcontainers.CustomizeRequest(containerTemplate))
	if err != nil {
		panic(err)
	}
	newConnection, err := mongodbContainer.ConnectionString(context.Background())
	if err != nil {
		panic(err)
	}
	println(newConnection)
	println("Waiting a minute...")
	time.Sleep(time.Minute)
}
```

**Comment by mdelapenya** [comment]
Hey @fkorotkov thanks for reporting this. I'd like to comment a few things:
- the config.AutoRemove fields comes from Docker, and according to their docs: it "automatically remove container when it exits", so because you try to set up a local dev mode, I think it's not needed to modify that value.
- the container is killed by Ryuk, our resource reaper, once there is no other connection signal from the container. So after a period of time Ryuk kills the container. Please see https://github.com/testcontainers/moby-ryuk#ryuk-configuration (Ryuk settings) and https://github.com/testcontainers/testcontainers-go/pull/1668 (how to configure Ryuk timeouts with testcontainers.properties file. See also https://golang.testcontainers.org/features/configuration/#supported-properties)

Said that, I think, for reuse, there is no clear documentation at the moment, so sorry for the confusion. We are internally having discussions for a more consistent approach for reuse mode, so it will eventually change to a more robust behaviour. In the mean time, for reuse you could disable Ryuk (probably not desired, or probably indeed desired, it depends of your use case).

I also recommend you taking a look at this workshop we are currently creating, specifically the section on local dev mode: https://github.com/testcontainers/workshop-go/blob/main/step-4-dev-mode-with-testcontainers.md. It could help you out in setting up the same.

Please let me know what you think 🙏
