### ISSUE TITLE
[Enhancement]: Add Target field to FromDockerfile struct

### ISSUE THREAD

**Issue by danvergara** [testcontainers/testcontainers-go#1926]
### Proposal

I've been trying to add `testcontainers` to my employer's CI, so my teammates can run integration tests. At some point, I needed to build a container image based off an existing `Dockerfile`, but the problem is that I need to specify a target stage to run the container in a test mode, where test dependencies are included.

I found out that [buildOptions](https://github.com/testcontainers/testcontainers-go/blob/480cadd123c9bd58506bbe34cf49592886d577f5/docker.go#L791C2-L791C14) is omitting the `Target` field, which is present in the [ImageBuildOptions](https://github.com/moby/moby/blob/2249db0c73433b5e3f34feabd9412e9948b955b7/api/types/client.go#L84) struct. Is there a reason to not expose this field?

**Comment by mdelapenya** [comment]
Hey @danvergara thanks for opening this issue. I've submitted #1931, which implements a mechanism for users to modify the image build options type if needed. That will simplify future additions, as instead of adding multiple methods to the FromDockerfile struct, we simply allow users to define the modifier with the changes, having access to the Docker type.

Of course, this change comes with a breaking change, which is caused by the need of adding a new method to the `ImageBuildInfo` interface. This is usually undesired, but will serve as preparation of a more stable API.
