### ISSUE TITLE
Use existing container?

### ISSUE THREAD

**Issue by SpencerC** [testcontainers/testcontainers-go#439]
Possibly a newbie question: is there a way to leave containers running between tests and reconnect to them rather than waiting for them to restart every time?

**Comment by mdelapenya** [comment]
Hi @SpencerC, you can keep containers alive after a test run simply passing a bool value to the container request: https://github.com/testcontainers/testcontainers-go/blob/dbb7f60fc0ded54a293adb11ff3097054b2fd495/container.go#L102

What I'm not sure is the main purpose of reusing containers between tests run: could you please elaborate a bit more? Ideally, a container should live alongside the test consuming it. You could define "test lifecycle hooks" beforeSuite/beforeTest depending of your testing framework, to keep containers running for a test suite/case. Please take a look at [Ginko](https://github.com/onsi/ginkgo) or [Godog](https://github.com/cucumber/godog), or use the Main function in the test package to control that.

In any case, it would be great if you can share with us your use case so we can find the best approach that works for you

**Comment by SpencerC** [comment]
Thanks @mdelapenya! I'm building some integration tests which rely on a container running a database, mirroring this pattern: https://github.com/stargate/stargate-grpc-go-client/blob/main/stargate/pkg/client/client_test.go#L45-L59

This particular container takes ~18 seconds to start. It would be nice to start it once, run the tests, have the option to explore the state in DataGrip, then reset it between tests using `DROP` or `TRUNCATE` commands. To be clear, I definitely see the benefit of test-specific containers for final CI testing. Just looking for a way to speed up local development.

Setting `SkipReaper` does indeed leave the container running, but then creates a new container for each test run.

Side note: https://www.youtube.com/watch?v=yi5A3cK1LNA. tldr: it's not a great idea to use external testing frameworks in Go. You can achieve the same effects using [subtests](https://pkg.go.dev/testing#T.Run), [`Cleanup`](https://pkg.go.dev/testing#T.Cleanup), and [Main](https://pkg.go.dev/testing#hdr-Main) (https://stackoverflow.com/questions/23729790/how-can-i-do-test-setup-using-the-testing-package-in-go).

CC: @mpenick

**Comment by mdelapenya** [comment]
>Side note: https://www.youtube.com/watch?v=yi5A3cK1LNA. tldr: it's not a great idea to use external testing frameworks in Go.

Well, as many many times in software engineering, it depends :) You could be needing gherkin to adhere to BDD principles, and need to parse gherkin files 🤷  But I agree: any external dependency must be cautiously added.

> Setting SkipReaper does indeed leave the container running, but then creates a new container for each test run.

Where did you create the container? If it's run in the Main function, it should be run only once.

Said that, I'd go with having the container in the Main function, and making sure all tests are creating/destroying their data in a very well decoupled manner, so that there are no interferences among them, including side effect caused by possible parallel execution.

> It would be nice to start it once, run the tests, have the option to explore the state in DataGrip, then reset it between tests using DROP or TRUNCATE commands.

I've used that pattern in the past, and I promise it's easy to find tests that "leak" corruption in the test suite. But once you are there, works like a charm!

Another side question I have is: why the container takes ~18 seconds to start? Is there a way to improve that?

**Comment by mdelapenya** [comment]
Ok, got it. And that it's expected because the container is attached to the `go test` execution. I was expecting you to run the  tests only once.

So your use case is that you want to keep a container for development purpose, always up meanwhile you code and eventually run tests, right?

Then I have say that testcontainers-go is not supporting that capability at this moment, but I'm checking that the Java folks have something for it https://github.com/testcontainers/testcontainers-java/blob/d93dceae969b63645b07881e80a61c57e3ca564b/core/src/main/java/org/testcontainers/containers/GenericContainer.java#L351. Pinging @kiview @bsideup for more context.

I'd prefer avoiding that reusability as much possible because it would go against the mantra of ephemeral containers, reproducibility, speed, and blahblahblah...  but if we see a possibility to cover your use case via configuration, them I'm 👍  to it.

**Comment by SpencerC** [comment]
> So your use case is that you want to keep a container for development purpose, always up meanwhile you code and eventually run tests, right?

Yes. I'd like one configuration that starts an ephemeral container for each run, and another that attempts to connect to an already running container (and creates one if none exists). It would be great if I could do this through testcontainers-go configuration options, but if this isn't possible I can add my own logic at the layer above.

One idea would be to enable this through the `Name` parameter. Currently, if I set a name and set `SkipReaper: true`, and re-run the tests I get an error saying:
```
error creating test backend: failed to start Stargate container: failed to start Stargate container: Error response from daemon: Conflict. The container name "/backend-test" is already in use by container "76ec90cbdaabd4cd27e2a052900255b21564f6482e616caaa0720e603e84bace". You have to remove (or rename) that container to be able to reuse that name.: failed to create container
```
Instead, perhaps it could just reconnect to that container?

**Comment by mdelapenya** [comment]
> Instead, perhaps it could just reconnect to that container?

That's my first thought, although I'd need to go more into the details from the Java repo. In any case, if you are interested in contributing a prototype, we will be more than happy to review it! 😄
